amcl:
  ros__parameters:
    use_map_topic: false
    base_frame_id: base_link
    global_frame_id: map
    odom_frame_id: odom

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0

controller_server:
  ros__parameters:
    expected_controller_frequency: 10.0

bt_navigator:
  ros__parameters:
    default_bt_xml_filename: "navigate_w_replanning_time2.xml"
