controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["wheel_fl_joint", "wheel_rl_joint"]
      right_wheel_names: ["wheel_fr_joint", "wheel_rr_joint"]
      publish_rate: 50
      wheel_separation: 0.3
      wheel_radius: 0.05
      use_stamped_vel: false
      cmd_vel_timeout: 0.5
      base_frame_id: base_link
      enable_odom_tf: true
