controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ['joint_wheel_fl', 'joint_wheel_rl']
    right_wheel_names: ['joint_wheel_fr', 'joint_wheel_rr']
    wheel_separation: 0.7
    wheel_radius: 0.1
    publish_rate: 30
    enable_odom_tf: true
